- hosts: minecraft
  become: yes
  tasks:
    - name: Download and install Java 21
      shell: |
        curl -L -o /tmp/corretto.tar.gz https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.tar.gz
        mkdir -p /opt/corretto
        tar -xzf /tmp/corretto.tar.gz -C /opt/corretto --strip-components=1
        alternatives --install /usr/bin/java java /opt/corretto/bin/java 1
      args:
        executable: /bin/bash
      when: not ansible_check_mode

    - name: Set Java 21 as default
      shell: |
        alternatives --install /usr/bin/java java /opt/corretto/bin/java 1
        alternatives --set java /opt/corretto/bin/java
      args:
        executable: /bin/bash

    - name: Verify Java version
      command: java -version

    - name: Install unzip and AWS CLI
      yum:
        name: 
          - unzip
          - awscli
        state: present
        
    - name: Create Minecraft directory
      file:
        path: /home/ec2-user/minecraft
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Download Minecraft Server 1.21.5
      get_url:
        url: "https://piston-data.mojang.com/v1/objects/6e64dcabba3c01a7271b4fa6bd898483b794c59b/server.jar"
        dest: /home/ec2-user/minecraft/server.jar
      when: not ansible_check_mode

    - name: Sync save file from S3
      shell: |
        aws s3 cp s3://$SPACELIFT_OUTPUT_minecraft_infra_s3_bucket/world.zip /home/ec2-user/minecraft/world.zip || true
        unzip -o /home/ec2-user/minecraft/world.zip -d /home/ec2-user/minecraft || true

    - name: Accept EULA
      copy:
        dest: /home/ec2-user/minecraft/eula.txt
        content: "eula=true"
      when: not ansible_check_mode

    - name: Set server.properties file
      copy:
        src: server.properties
        dest: /home/ec2-user/minecraft/server.properties
        mode: '0644'
        owner: ec2-user
        group: ec2-user

    - name: Start Minecraft Server
      shell: |
        cd /home/ec2-user/minecraft
        nohup java -Xmx1024M -Xms1024M -jar server.jar nogui &
      when: not ansible_check_mode
