- hosts: minecraft
  become: yes
  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Install unzip and AWS CLI
      yum:
        name: 
          - unzip
          - awscli
        state: present

    - name: Create Minecraft directory
      file:
        path: /home/ec2-user/minecraft
        state: directory

    - name: Download Minecraft Server 1.21.5
      get_url:
        url: "https://launcher.mojang.com/v1/objects/59ff2c63ec218dc718a07b6d88c27b3fcd7fdf46/server.jar"
        dest: /home/ec2-user/minecraft/server.jar

    - name: Sync save file from S3
      shell: |
        aws s3 cp s3://$SPACELIFT_OUTPUT_minecraft_infra_s3_bucket/world.zip /home/ec2-user/minecraft/world.zip || true
        unzip -o /home/ec2-user/minecraft/world.zip -d /home/ec2-user/minecraft || true

    - name: Accept EULA
      copy:
        dest: /home/ec2-user/minecraft/eula.txt
        content: "eula=true"

    - name: Start Minecraft Server
      shell: |
        cd /home/ec2-user/minecraft
        nohup java -Xmx1024M -Xms1024M -jar server.jar nogui &
