# config/save-world.yml
- hosts: minecraft
  become: true
  tasks:
    - name: Zip Minecraft world directory
      shell: |
        cd /home/ec2-user/minecraft
        zip -r world.zip world || true

    - name: Upload zipped world to current S3 bucket
      shell: |
        aws s3 cp /home/ec2-user/minecraft/world.zip s3://{{ lookup('env', 's3_bucket') }}/world.zip
